### PR TITLE
feat:components titles add title bold and title font size style attributes

### PR DESCRIPTION
**Pull request by ryoakirasan**
## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.   
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes
What types of changes does your code introduce to Lowcoder?  
_Put an `x` in the boxes that apply._

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist
You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! 
This is simply a reminder of what we are going to look for before merging your code.  
_Put an `x` in the boxes that apply._

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc.

### CODE REVIEW

**Comment by falnyr** [comment]
Can you please resolve the conflicts?

**Comment by ryoakirasan** [comment]
> Can you please resolve the conflicts?

:joy:I haven't used git as a collaboration before, what part is conflicting?
How can I resolve my conflicts?

**Comment by falnyr** [comment]
> > Can you please resolve the conflicts?
> 
> 😂I haven't used git as a collaboration before, what part is conflicting? How can I resolve my conflicts?

If you haven't dealt with conflicts before, please read this: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts

**Comment by ryoakirasan** [comment]
> > > Can you please resolve the conflicts?
> > 
> > 
> > 😂I haven't used git as a collaboration before, what part is conflicting? How can I resolve my conflicts?
> 
> If you haven't dealt with conflicts before, please read this: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts

I have executed the command and resubmitted. But it still prompts a conflict.

**Comment by FalkWolsky** [comment]
@ryoakirasan, could you please add yarn.lock to gitignore? 
It should not be part of the commit. Thank you very much!

**Comment by LennardF1989** [comment]
> It should not be part of the commit.
This is not true though: https://classic.yarnpkg.com/en/docs/migrating-from-npm

> When you run either yarn or yarn add <package>, Yarn will generate a yarn.lock file within the root directory of your package. You don’t need to read or understand this file - **just check it into source control**. When other people start using Yarn instead of npm, the yarn.lock file will ensure that they get precisely the same dependencies as you have.

**Comment by FalkWolsky** [comment]
I see. How we handle the merge conflicts then? If I memorize right, there were 65 conflicts in yarn.lock

**Comment by LennardF1989** [comment]
> I see. How we handle the merge conflicts then? If I memorize right, there were 65 conflicts in yarn.lock

Just take either file when resolving conflict, re-run "yarn install" to update it to the latest state, and commit the result. 

Merge conflicts will only happen if multiple people touch the package.json. In that case, the yarn.lock (as well as package-lock.json) will have to be fully rebuild.

**Pull request closed without merging**
