### PR TITLE
Feature/generic oauth

### PR DESCRIPTION
**Pull request by th37rose**
## Proposed changes
- Generate final url in backend using placeholders
- Allow adding multiple auth provider with same authType

## Types of changes
What types of changes does your code introduce to Lowcoder?  
_Put an `x` in the boxes that apply._

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist
You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! 
This is simply a reminder of what we are going to look for before merging your code.  
_Put an `x` in the boxes that apply._

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc.

### CODE REVIEW

**Comment by ludomikula** [comment]
Merged as a separate commit.

**Comment by lanedsmu** [comment]
@th37rose, can absolutely take this conversation elsewhere. Had some questions about generic oauth:
* is it possible to reference ID token attributes as well as userinfo attributes in mapping?  (MS's userinfo endpoint in particular is very sparse).  If so what's the way to make that happen?
* is it possible to craft the redirect URL such that the redirect will come back to the originating (app) url?  By that I mean: if I browse directly to a lowcoder app, and I'm unauthenticated, it'd be great to be redirected to the OIDC provider login, and then back to the app (ultimately), rather than going to a lowcoder homepage (or even a lowcoder login prompt, really).
* is it possible to craft a url that'd go directly to the OIDC provider?  I'd love to be able to bypass the lowcoder login prompt altogether, if possible...

Thanks!

**Comment by th37rose** [comment]
@lanedsmu 
- is it possible to reference ID token attributes as well as userinfo attributes in mapping? (MS's userinfo endpoint in particular is very sparse). If so what's the way to make that happen?
Sure, it can map userinfo from MS-OAuth userinfo endpoint into AuthUser class using mapping provided by provider config.

- is it possible to craft the redirect URL such that the redirect will come back to the originating (app) url? By that I mean: if I browse directly to a lowcoder app, and I'm unauthenticated, it'd be great to be redirected to the OIDC provider login, and then back to the app (ultimately), rather than going to a lowcoder homepage (or even a lowcoder login prompt, really).
Redirect url should be configured when adding provider in the `Setting`->`User Authentication` and only configured redirect url should be used. Otherwise, authorization from provider wil fail.

- is it possible to craft a url that'd go directly to the OIDC provider? I'd love to be able to bypass the lowcoder login prompt altogether, if possible...
There is backend api to get provider configuration info, so you can craft url using the provided configuration.

**Comment by lanedsmu** [comment]
Thanks much for the time here!
Wrt user info, what I'm asking is if it's possible to use attributes from the ID token in addition to the user info endpoint. Ms's userinfo endpoint only has: sub",     "name",     "family_name",     "given_name",     "picture",     "email"
and it's not extensible. What we're needing is additional attributes that are exposed in the id and access tokens, and I'm wondering if we can access those in the user mapping. If so, how to reference those? In another app, for instance, these are accessible using {id.attrubute} banking.

I understand the need to be able to configure the redirect uri in the id provider settings; what I'm hoping we can accomplish in lowcoder is what other apps have done, in which when you browse to a particular app; you're redirected to the right auth provider automatically; and after authentication, you are brought back to the url you originally requested, rather than to a  central landing page. I believe this is usually done either with url parameters or cookies, tho I confess I've never coded such a thing....

Thanks much for the hint on the api endpoint; we'll look at that and see if that might help us in accomplishing some of this.

Does the additional info on those first two items make sense, and do you have some ideas or hints on if it's possible to accomplish those?  - Lane


________________________________

**Comment by lanedsmu** [comment]
Thanks much for the time here! 
Wrt user info, what I'm asking is if it's possible to use attributes from the ID token in addition to the user info endpoint. Ms's userinfo endpoint only has: "sub",     "name",     "family_name",     "given_name",     "picture",     "email"
and it's not extensible. What we're needing is additional attributes that are exposed in the id and access tokens, and I'm wondering if we can access those in the user mapping. If so, how to reference those? In another app, for instance, these are accessible using {id.attrubute} reference. 


I understand the need to be able to configure the redirect uri in the id provider settings; what I'm hoping we can accomplish in lowcoder is what other apps have done, in which when you browse to a particular app; you're redirected to the right auth provider automatically; and after authentication, you are brought back to the url you originally requested, rather than to a  central landing page. I believe this is usually done either with url parameters or cookies, tho I confess I've never coded such a thing.... 

Thanks much for the hint on the api endpoint; we'll look at that and see if that might help us in accomplishing some of this.  

Does the additional info on those first two items make sense, and do you have some ideas or hints on if it's possible to accomplish those?  - Lane

**Pull request closed without merging**
